// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SahayaSetu.Data;

#nullable disable

namespace SahayaSetu.Migrations
{
    [DbContext(typeof(MyAppDbContext))]
    [Migration("20260202133445_MySqlSync")]
    partial class MySqlSync
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SahayaSetu.Models.Donation", b =>
                {
                    b.Property<int>("DonationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DonationId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DonatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DonorId")
                        .HasColumnType("int");

                    b.Property<int>("FundraiserRequestId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentMode")
                        .HasColumnType("int");

                    b.Property<string>("PaymentReference")
                        .HasColumnType("longtext");

                    b.Property<string>("ResponseMessage")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ResponseSentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("ResponseStatus")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("DonationId");

                    b.HasIndex("DonorId");

                    b.HasIndex("FundraiserRequestId");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("SahayaSetu.Models.Donor", b =>
                {
                    b.Property<int>("DonorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DonorId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DonorId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Donors");
                });

            modelBuilder.Entity("SahayaSetu.Models.FundraiserRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<decimal>("CollectedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RequestId");

                    b.ToTable("FundraiserRequests");
                });

            modelBuilder.Entity("SahayaSetu.Models.NGO", b =>
                {
                    b.Property<int>("NgoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NgoId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DarpanId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("NgoId");

                    b.ToTable("NGOs");
                });

            modelBuilder.Entity("SahayaSetu.Models.Request", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NgoId")
                        .HasColumnType("int");

                    b.Property<int>("RequestType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("RequestId");

                    b.HasIndex("NgoId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("SahayaSetu.Models.ResourceContribution", b =>
                {
                    b.Property<int>("ContributionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ContributionId"));

                    b.Property<DateTime>("ContributedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DonorId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ResourceRequestId")
                        .HasColumnType("int");

                    b.HasKey("ContributionId");

                    b.HasIndex("DonorId");

                    b.HasIndex("ResourceRequestId");

                    b.ToTable("ResourceContributions");
                });

            modelBuilder.Entity("SahayaSetu.Models.ResourceRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityReceived")
                        .HasColumnType("int");

                    b.Property<int>("QuantityRequired")
                        .HasColumnType("int");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RequestId");

                    b.ToTable("ResourceRequests");
                });

            modelBuilder.Entity("SahayaSetu.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SahayaSetu.Models.VolunteerParticipation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DonorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("VolunteerRequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonorId");

                    b.HasIndex("VolunteerRequestId");

                    b.ToTable("VolunteerParticipations");
                });

            modelBuilder.Entity("SahayaSetu.Models.VolunteerRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("SkillsRequired")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("VolunteersRequired")
                        .HasColumnType("int");

                    b.HasKey("RequestId");

                    b.ToTable("VolunteerRequests");
                });

            modelBuilder.Entity("SahayaSetu.Models.Donation", b =>
                {
                    b.HasOne("SahayaSetu.Models.Donor", "Donor")
                        .WithMany()
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SahayaSetu.Models.FundraiserRequest", "FundraiserRequest")
                        .WithMany()
                        .HasForeignKey("FundraiserRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Donor");

                    b.Navigation("FundraiserRequest");
                });

            modelBuilder.Entity("SahayaSetu.Models.Donor", b =>
                {
                    b.HasOne("SahayaSetu.Models.User", "User")
                        .WithOne("Donor")
                        .HasForeignKey("SahayaSetu.Models.Donor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SahayaSetu.Models.FundraiserRequest", b =>
                {
                    b.HasOne("SahayaSetu.Models.Request", "Request")
                        .WithOne("FundraiserRequest")
                        .HasForeignKey("SahayaSetu.Models.FundraiserRequest", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("SahayaSetu.Models.Request", b =>
                {
                    b.HasOne("SahayaSetu.Models.NGO", "NGO")
                        .WithMany("Requests")
                        .HasForeignKey("NgoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NGO");
                });

            modelBuilder.Entity("SahayaSetu.Models.ResourceContribution", b =>
                {
                    b.HasOne("SahayaSetu.Models.Donor", "Donor")
                        .WithMany()
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SahayaSetu.Models.ResourceRequest", "ResourceRequest")
                        .WithMany()
                        .HasForeignKey("ResourceRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Donor");

                    b.Navigation("ResourceRequest");
                });

            modelBuilder.Entity("SahayaSetu.Models.ResourceRequest", b =>
                {
                    b.HasOne("SahayaSetu.Models.Request", "Request")
                        .WithOne("ResourceRequest")
                        .HasForeignKey("SahayaSetu.Models.ResourceRequest", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("SahayaSetu.Models.VolunteerParticipation", b =>
                {
                    b.HasOne("SahayaSetu.Models.Donor", "Donor")
                        .WithMany("VolunteerParticipations")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SahayaSetu.Models.VolunteerRequest", "VolunteerRequest")
                        .WithMany("VolunteerParticipations")
                        .HasForeignKey("VolunteerRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donor");

                    b.Navigation("VolunteerRequest");
                });

            modelBuilder.Entity("SahayaSetu.Models.VolunteerRequest", b =>
                {
                    b.HasOne("SahayaSetu.Models.Request", "Request")
                        .WithOne("VolunteerRequest")
                        .HasForeignKey("SahayaSetu.Models.VolunteerRequest", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("SahayaSetu.Models.Donor", b =>
                {
                    b.Navigation("VolunteerParticipations");
                });

            modelBuilder.Entity("SahayaSetu.Models.NGO", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("SahayaSetu.Models.Request", b =>
                {
                    b.Navigation("FundraiserRequest");

                    b.Navigation("ResourceRequest");

                    b.Navigation("VolunteerRequest");
                });

            modelBuilder.Entity("SahayaSetu.Models.User", b =>
                {
                    b.Navigation("Donor");
                });

            modelBuilder.Entity("SahayaSetu.Models.VolunteerRequest", b =>
                {
                    b.Navigation("VolunteerParticipations");
                });
#pragma warning restore 612, 618
        }
    }
}
